name: CI

on: 
  push: 
    branches: [ main ]
    paths: 
      - '!**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
    - name: run tests
      run: |
        go test -run '^[^TestCanonical]'